language: go

go:
  - 1.13.x
install:
  - go get github.com/mattn/goveralls
script:
  - go test -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken rnyyoMiNvWP9k0esrKr1VPtF4g9u00EPg
